runtime: nodejs
env: flex
resources:
  cpu: 1
  memory_gb: 0.6
env_variables:
  ENV: PROD
beta_settings:
  cloud_sql_instances: mindera-openday:us-central1:mindera-people
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1